ALTER TABLE browser_sessions ADD COLUMN IF NOT EXISTS visitor_id TEXT NULL;
ALTER TABLE browser_sessions ADD COLUMN IF NOT EXISTS user_identifier TEXT NULL;
ALTER TABLE browser_sessions ADD COLUMN IF NOT EXISTS context JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE browser_sessions ADD COLUMN IF NOT EXISTS events JSONB DEFAULT '[]'::jsonb;

ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS site_key TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS visitor_id TEXT NULL;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS max_scroll_depth INTEGER NULL;

ALTER TABLE sdk_events ADD COLUMN IF NOT EXISTS visitor_id TEXT NULL;
ALTER TABLE sdk_events ADD COLUMN IF NOT EXISTS event_name TEXT NULL;
ALTER TABLE sdk_events ADD COLUMN IF NOT EXISTS context JSONB NOT NULL DEFAULT '{}'::jsonb;
