name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Derive appropriate SHAs for help Nx calculate affected
        uses: nrwl/nx-set-shas@v4

      - name: Lint Affected
        run: npx nx affected -t lint --parallel=3

      - name: Test Affected
        run: npx nx affected -t test --parallel=3 --ci --code-coverage

      - name: Build Affected
        run: npx nx affected -t build --parallel=3
